// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-XU-hkaFPVVenG0tuzIDQWHKirj79xHY',
    appId: '1:685814496914:web:70b82e49b1f4eb789eb04b',
    messagingSenderId: '685814496914',
    projectId: 'ecointerior-20242',
    authDomain: 'ecointerior-20242.firebaseapp.com',
    storageBucket: 'ecointerior-20242.appspot.com',
    measurementId: 'G-HRSYKDMVXZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCouEC4ieWu9BQVaOhoFwoJ3DwYkOMBsCc',
    appId: '1:685814496914:android:bb5f39a0e5a6e7d59eb04b',
    messagingSenderId: '685814496914',
    projectId: 'ecointerior-20242',
    storageBucket: 'ecointerior-20242.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn-9fIIjocfWgss9PxTo6nWmRfBbiauLE',
    appId: '1:685814496914:ios:8cad365343cddef99eb04b',
    messagingSenderId: '685814496914',
    projectId: 'ecointerior-20242',
    storageBucket: 'ecointerior-20242.appspot.com',
    iosBundleId: 'com.example.ecointerior',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-XU-hkaFPVVenG0tuzIDQWHKirj79xHY',
    appId: '1:685814496914:web:9eaf6fa8054e565c9eb04b',
    messagingSenderId: '685814496914',
    projectId: 'ecointerior-20242',
    authDomain: 'ecointerior-20242.firebaseapp.com',
    storageBucket: 'ecointerior-20242.appspot.com',
    measurementId: 'G-34RDWQKY4L',
  );

}